# Random Value generation with tensorflow is explained here
[ReferenceDocs](https://www.tensorflow.org/api_guides/python/constant_op)

In [3]:
import tensorflow as tf

In [26]:
sess = tf.InteractiveSession()

X = tf.random_normal([3,3], mean=1, stddev=3, dtype=tf.float32)
print(X.eval() * 1)
print(type(X))


X = tf.random_uniform((3, 3), minval=1, maxval=10, dtype=tf.int64)
print(X.eval())
print(type(X))

sess.close()

[[ 0.49718082  0.67853975 -6.4662304 ]
 [-4.698241   -0.29813325 -1.7903368 ]
 [-1.0691097   2.0692015   1.1159183 ]]
<class 'tensorflow.python.framework.ops.Tensor'>
[[5 6 5]
 [8 4 3]
 [7 4 3]]
<class 'tensorflow.python.framework.ops.Tensor'>


C:\Users\nandpara\AppData\Roaming\Python\Python36\site-packages\tensorflow\python\client\session.py:1662: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '
